### PR TITLE
Make this module installable using pip

### PR DESCRIPTION
**Pull request by methadata**
We have performed the minimal changes needed to be able to install this module using pip2.
This way, the module follows the standard procedure for installing any module, and it's more community-friendly.

Please notice that there has been no modification in functionality. We've only modified the structure in directories and created the `setup.py` file needed for pip to be able to install the package.

### CODE REVIEW

**Comment by methadata** [comment]
Notice that this PR breaks compatibility with Ansible module.
The Ansible module shouldn't have the SDK path hardoced in it. We can send another PR with the changes needed for the Ansilble Module to work with the proposed structure.

**Comment by chkp-wbelt** [comment]
Are there any plans to merge this functionality?  Just trying to minimize the number of scripts utilizing the

`
from cp_mgmt_api_python_sdk.lib import APIClient, APIClientArgs
`

method for importing which this merge corrects to be more typical of python libraries.

**Comment by chkp-amiads** [comment]
We are checking the option of supporting:
pip install git+https://github.com/chkp-yaelg/cp_mgmt_api_python_sdk.git

**Comment by chkp-amiads** [comment]
By mid Feb we will make our SDK 
pip install git+https://github.com/CheckPointSW/cp_mgmt_api_python_sdk.git 

I'm kindly closing this pull request

**Pull request closed without merging**
