### PR TITLE
add offset option to gen_api_query

### PR DESCRIPTION
**Pull request by aque**
The offset option is used on [show-generic-objects command](https://gist.github.com/aque/7e409e91121277b5ce2e94dc9f9577f2).

### CODE REVIEW

**Comment by chkp-yaelg** [comment]
Hi @aque ,
Thank you for sharing.
Why are you using gen_api_query command instead of api_query?

Try this:
`client.api_query(command="show-generic-objects", payload={"name":"obj_name"} `(and the rest of your payload)

Also, a small correction for your fix in line 431:
`if received_objects == (total_objects + offset):` 
This should be:
`if received_objects == total_objects:`
since the "total" represents the total objects that the query found and it is not depend on the "limit" or "offset" values.

**Comment by aque** [comment]
Hi @chkp-yaelg,

My objective is to get a list of User objects from our SmartCenter running R80.20 T118. When I try `result = client.api_query(command="show-generic-objects", payload={"class-name": "com.checkpoint.objects.classes.dummy.CpmiUser"})`, I get:

    >>> len(result.data)
    50

    >>> result.res_obj["data"]["total"]
    50

When I use `client.api_query(command="show-hosts")`, I get a dict with all 4800+ objects. This is not the case with above and it is why I had to use `gen_api_query()` with `offset`. That was the only way I could get it to work.

As for line 431, you are correct. `total_objects` contains the full count and `offset` is not needed here. However, with `command="show-generic-objects"`, `total_objects` is 50 even though I have over 1700+ User objects in the system. Removing `offset` caused a `KeyError: 'to'` exception when it reached the end.

Could I be running into an API bug and that query is not returning the full object count in `api_res.data["total"]` (line 423)? This explains why `api_query()` does not return the full list.

**Comment by aque** [comment]
I updated my PR and removed `offset` from line 431.

**Comment by chkp-yaelg** [comment]
@aque , looks like a good solution. 
Also, you can use the `api_call` function with your limit and offset in the payload.

The generic-objects are not officially supported, and can behave differently then the official queries.
This is not a bug but I will take it internally and check if we can make it behave like the other queries.
We are planning to release new API for user objects in the upcoming versions.

Thanks again 
Management API team

**Comment by aque** [comment]
Thanks for merging the PR @chkp-yaelg! I'll try the offset with `api_call`.

**Pull request merged**
